version: '2'

services:
  db:
    container_name: 'db'
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'appdb'
       MYSQL_PASSWORD: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - 'db:/var/lib/mysql'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6378:6379'
    volumes:
      - 'redisdata:/data'
  memcached:
    container_name: 'memcached'
    image: 'memcached:latest'
    ports:
      - "11212:11211"
  web:
    build: .
    command: python3 app/manage.py runserver 0.0.0.0:8001 
    volumes:
      - '.:/base_directory'
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
      - memcached

volumes:
  redisdata:
  db:
  .: