version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: '54985498'
      MYSQL_DATABASE: 'bankapidb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '54985498'
