# Generated by Django 3.2.12 on 2023-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
