# Generated by Django 3.2.12 on 2023-06-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('balance', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='account_entries', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='Account_entry_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='account_entry', to='transactions.account'),
        ),
    ]
