# Generated by Django 3.2.12 on 2023-06-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('transactions', '0002_auto_20230618_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Account_entry_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='users.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Account_entry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='account_entry', to='transactions.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.user'),
        ),
    ]
